Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:
a) Addition of 2 in all the element
b) Multiply 3 with all the elements
c) Divide every element by 2



In [7]:
import numpy as np

In [9]:

a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [11]:
#a.
c=[]
for i in range(len(a)):
    c.append(a[i]+2)
print(c)
    

[3, 4, 5, 6, 7]


In [13]:
#b.
d=[]
for i in range(len(a)):
    d.append(a[i]*3)
print(d)

[3, 6, 9, 12, 15]


In [15]:
#c.
e=[]
for i in range(len(a)):
    e.append(a[i]//2)
print(e)

[0, 1, 1, 2, 2]


Q.2 Questions on Basic NumPy Array:
a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
b) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [18]:
arr=np.array([1,2,3,6,4,5])
print(arr)

[1 2 3 6 4 5]


In [20]:
#a.
arr1=[]
for i in reversed(range(len(arr))):
    arr1.append(arr[i])
print(arr1)

[5, 4, 6, 3, 2, 1]


In [22]:
#b.
from collections import Counter
x=np.array([1,2,3,4,5,1,2,1,1,1])
count=Counter(x)
mostfrequent,_=count.most_common(1)[0]
indices=np.where(x==mostfrequent)[0]
print("most frequent value is :",mostfrequent)
print("index of most frequent value are:",indices)

most frequent value is : 1
index of most frequent value are: [0 5 7 8 9]


In [24]:
from collections import Counter
y=np.array([1,1,1,2,3,4,2,4,3,3])
curr=Counter(y)
most_frequent,_=curr.most_common(1)[0]
indices1=np.where(y==most_frequent)[0]
print("most frequent value is :",most_frequent)
print("index of most frequent value are:",indices1)


most frequent value is : 1
index of most frequent value are: [0 1 2]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:
a) Access 1st row, 2nd column
b) Access 3rd row, 1st column


In [27]:
import numpy as np
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])


In [29]:
#3.1
element_a=arr[0,1]
print(element_a)

20


In [31]:
#3.2
element_b=arr[2,0]
print(element_b)

70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [36]:
swastik=np.linspace(10,100,25)
print("array:",swastik)
print("dimension of the array:",swastik.ndim)
print("shape:",swastik.shape)
print("total elements:",swastik.size)
print("data type:",swastik.dtype)
print("no of bytes:",swastik.nbytes)
reshape_array=swastik.reshape(25,1)
transpose_array=reshape_array.T
print(transpose_array)
direct_transpose=swastik.T
print(direct_transpose)

array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
dimension of the array: 1
shape: (25,)
total elements: 25
data type: float64
no of bytes: 200
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.

In [43]:

ucs420_swastik=np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
print(np.mean(ucs420_swastik))
print(np.median(ucs420_swastik))
print(np.max(ucs420_swastik))
print(np.min(ucs420_swastik))
print(np.unique(ucs420_swastik))
reshaped_ucs420_swastik=ucs420_swastik.reshape(4,3)
print(reshaped_ucs420_swastik)
resized_ucs420_swastik=np.resize(ucs420_swastik,(2,3))
print(resized_ucs420_swastik)

43.333333333333336
37.5
90
10
[10 15 20 30 35 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
[[10 20 30]
 [40 50 60]]
